export const mockGroups = [
  {
    id: 'gemini-elite',
    name: 'Gemini Elite Creators',
    owner: '@geminiowner',
    ownerName: 'Gemini Owner',
    commission: 10,
    members: 42,
    description: 'A premium creator group offering professional management, marketing support, and transparent commission structures for serious content creators.',
    benefits: ['Dedicated account manager', 'Marketing support', 'Priority support', 'Weekly performance reports'],
    avatar: 'https://images.unsplash.com/photo-1614850523459-c2f4c699c52e?w=80&h=80&fit=crop',
    banner: 'https://images.unsplash.com/photo-1614850523459-c2f4c699c52e?w=800&h=200&fit=crop',
    featured: true,
    status: 'open',
  },
  {
    id: 'luxe-house',
    name: 'Luxe Creator House',
    owner: '@luxemanager',
    ownerName: 'Luxe Manager',
    commission: 12,
    members: 28,
    description: 'An exclusive group for creators who want premium brand positioning, high-quality production support, and a luxury platform experience.',
    benefits: ['Brand positioning', 'Production support', 'Exclusive events', 'High-value campaigns'],
    avatar: 'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=80&h=80&fit=crop',
    banner: 'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=800&h=200&fit=crop',
    featured: false,
    status: 'open',
  },
  {
    id: 'velvet-circle',
    name: 'Velvet Circle',
    owner: '@velvetlead',
    ownerName: 'Velvet Lead',
    commission: 8,
    members: 65,
    description: 'The largest creator collective on the platform. Low commission, community-driven, with strong peer support and regular group challenges.',
    benefits: ['Low commission rate', 'Community support', 'Monthly challenges', 'Group content collabs'],
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop',
    banner: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=200&fit=crop',
    featured: false,
    status: 'open',
  },
  {
    id: 'nova-collective',
    name: 'Nova Collective',
    owner: '@novaowner',
    ownerName: 'Nova Owner',
    commission: 15,
    members: 18,
    description: 'A boutique group focused on high-earning creators. Higher commission in exchange for intensive one-on-one management and growth campaigns.',
    benefits: ['1-on-1 management', 'Growth campaigns', 'Ad spend included', 'VIP creator events'],
    avatar: 'https://images.unsplash.com/photo-1519764622345-23439dd774f7?w=80&h=80&fit=crop',
    banner: 'https://images.unsplash.com/photo-1519764622345-23439dd774f7?w=800&h=200&fit=crop',
    featured: false,
    status: 'open',
  },
];

export const mockCreatorState = {
  status: 'active_member', // 'no_group' | 'join_requested' | 'active_member' | 'leave_requested' | 'removed'
  groupId: 'gemini-elite',
  groupName: 'Gemini Elite Creators',
  groupOwner: '@geminiowner',
  dateJoined: '2026-01-15',
  advertisedRate: 10,
  currentRate: 12,
  platformFee: 30,
  netEarnings: 58,
  leaveRequestedAt: null,
  pendingCommissionChange: {
    oldRate: 12,
    newRate: 14,
    requestedAt: '2026-04-28T10:00:00Z',
    status: 'pending',
  },
};

export const mockMembers = [
  {
    id: 'creator-1',
    username: '@amyrose',
    name: 'Amy Rose',
    avatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b37c?w=60&h=60&fit=crop&crop=face',
    accountStatus: 'active',
    membershipStatus: 'active',
    commission: 12,
    netEarnings: 58,
    salesThisMonth: 3240,
    ownerCommissionEarned: 388.80,
    dateJoined: '2026-01-15',
    totalSales: 18900,
  },
  {
    id: 'creator-2',
    username: '@lola',
    name: 'Lola',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=60&h=60&fit=crop&crop=face',
    accountStatus: 'hidden',
    membershipStatus: 'active',
    commission: 10,
    netEarnings: 60,
    salesThisMonth: 1890,
    ownerCommissionEarned: 189,
    dateJoined: '2026-02-01',
    totalSales: 9200,
  },
  {
    id: 'creator-3',
    username: '@miasky',
    name: 'Mia Sky',
    avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=60&h=60&fit=crop&crop=face',
    accountStatus: 'active',
    membershipStatus: 'leave_requested',
    commission: 15,
    netEarnings: 55,
    salesThisMonth: 2100,
    ownerCommissionEarned: 315,
    dateJoined: '2026-01-20',
    totalSales: 12400,
    leaveCountdown: '18h 20m',
  },
  {
    id: 'creator-4',
    username: '@stellanova',
    name: 'Stella Nova',
    avatar: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=60&h=60&fit=crop&crop=face',
    accountStatus: 'deactivated',
    membershipStatus: 'active',
    commission: 10,
    netEarnings: 60,
    salesThisMonth: 0,
    ownerCommissionEarned: 0,
    dateJoined: '2026-03-05',
    totalSales: 4500,
  },
  {
    id: 'creator-5',
    username: '@rubygrace',
    name: 'Ruby Grace',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=60&h=60&fit=crop&crop=face',
    accountStatus: 'active',
    membershipStatus: 'active',
    commission: 8,
    netEarnings: 62,
    salesThisMonth: 4800,
    ownerCommissionEarned: 384,
    dateJoined: '2025-12-01',
    totalSales: 29000,
  },
];

export const mockJoinRequests = [
  {
    id: 'req-1',
    username: '@nikkilane',
    name: 'Nikki Lane',
    avatar: 'https://images.unsplash.com/photo-1542596594-649edbc13630?w=60&h=60&fit=crop&crop=face',
    requestedAt: '2026-04-29T14:22:00Z',
    accountStatus: 'active',
    followers: 4200,
    avgMonthlyEarnings: 2800,
    contentTypes: ['Photos', 'Videos'],
  },
  {
    id: 'req-2',
    username: '@daisymae',
    name: 'Daisy Mae',
    avatar: 'https://images.unsplash.com/photo-1546961342-ea5f62d856a1?w=60&h=60&fit=crop&crop=face',
    requestedAt: '2026-04-28T09:11:00Z',
    accountStatus: 'active',
    followers: 7800,
    avgMonthlyEarnings: 5100,
    contentTypes: ['Live Cams', 'Photos', 'Subscriptions'],
  },
  {
    id: 'req-3',
    username: '@crystalblue',
    name: 'Crystal Blue',
    avatar: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=60&h=60&fit=crop&crop=face',
    requestedAt: '2026-04-27T16:45:00Z',
    accountStatus: 'active',
    followers: 2100,
    avgMonthlyEarnings: 1400,
    contentTypes: ['Videos', 'Text Chat'],
  },
];

export const mockTransactions = [
  { id: 'txn-001', date: '2026-04-29', type: 'Live Cam', gross: 100, platformFee: 30, groupCommission: 12, creatorAmount: 58 },
  { id: 'txn-002', date: '2026-04-28', type: 'Photo Sale', gross: 50, platformFee: 10, groupCommission: 6, creatorAmount: 34 },
  { id: 'txn-003', date: '2026-04-27', type: 'Tip', gross: 25, platformFee: 5, groupCommission: 3, creatorAmount: 17 },
  { id: 'txn-004', date: '2026-04-26', type: 'Subscription', gross: 15, platformFee: 3, groupCommission: 1.80, creatorAmount: 10.20 },
  { id: 'txn-005', date: '2026-04-25', type: 'Live Cam', gross: 200, platformFee: 60, groupCommission: 24, creatorAmount: 116 },
  { id: 'txn-006', date: '2026-04-24', type: 'Video Sale', gross: 30, platformFee: 6, groupCommission: 3.60, creatorAmount: 20.40 },
];

export const mockNotifications = [
  { id: 'n-1', type: 'join_request', title: 'New Join Request', description: '@nikkilane has requested to join your group', time: '2 hours ago', status: 'unread', action: 'View Request' },
  { id: 'n-2', type: 'commission_change', title: 'Commission Approval Needed', description: 'Commission change request for @amyrose requires your approval', time: '4 hours ago', status: 'unread', action: 'Review' },
  { id: 'n-3', type: 'leave_request', title: 'Creator Leaving', description: '@miasky has started a leave request. 18h 20m remaining.', time: '6 hours ago', status: 'read', action: 'View' },
  { id: 'n-4', type: 'account_hidden', title: 'Account Hidden', description: '@lola has hidden their account', time: '1 day ago', status: 'read', action: 'View Creator' },
  { id: 'n-5', type: 'join_approved', title: 'Request Approved', description: 'Your request to join Gemini Elite Creators has been approved', time: '3 days ago', status: 'read', action: null },
];

export const mockActivityHistory = [
  { id: 'act-1', event: 'Join Request Approved', actor: '@geminiowner', target: '@amyrose', group: 'Gemini Elite Creators', oldValue: null, newValue: 'Active Member', timestamp: '2026-01-15T10:00:00Z' },
  { id: 'act-2', event: 'Commission Change Requested', actor: '@geminiowner', target: '@amyrose', group: 'Gemini Elite Creators', oldValue: '10%', newValue: '12%', timestamp: '2026-02-10T14:30:00Z' },
  { id: 'act-3', event: 'Commission Change Approved', actor: '@amyrose', target: '@amyrose', group: 'Gemini Elite Creators', oldValue: '10%', newValue: '12%', timestamp: '2026-02-11T09:15:00Z' },
  { id: 'act-4', event: 'Profile Hidden', actor: '@lola', target: '@lola', group: 'Gemini Elite Creators', oldValue: 'Active', newValue: 'Hidden', timestamp: '2026-04-20T16:00:00Z' },
  { id: 'act-5', event: 'Leave Request Started', actor: '@miasky', target: '@miasky', group: 'Gemini Elite Creators', oldValue: 'Active Member', newValue: 'Leave Requested', timestamp: '2026-04-30T08:00:00Z' },
  { id: 'act-6', event: 'Image Uploaded by Group Owner', actor: '@geminiowner', target: '@amyrose', group: 'Gemini Elite Creators', oldValue: null, newValue: 'summer_set_01.jpg', timestamp: '2026-04-22T11:00:00Z' },
  { id: 'act-7', event: 'Join Request Submitted', actor: '@nikkilane', target: '@nikkilane', group: 'Gemini Elite Creators', oldValue: null, newValue: 'Pending', timestamp: '2026-04-29T14:22:00Z' },
];